### ISSUE TITLE
使用报错，不知道怎么处理，

### ISSUE THREAD

**Issue by xiaohuoni** [amazeui/amazeui-touch#104]
## 问题描述

Error: Cannot find module 'react-addons-css-transition-group' from 'F:\CrowdSourcing\src\h5\node_modules\amazeui-touch\lib'
    at F:\CrowdSourcing\src\h5\node_modules\resolve\lib\async.js:46:17
    at process (F:\CrowdSourcing\src\h5\node_modules\resolve\lib\async.js:173:43)
    at ondir (F:\CrowdSourcing\src\h5\node_modules\resolve\lib\async.js:188:17)
    at load (F:\CrowdSourcing\src\h5\node_modules\resolve\lib\async.js:69:43)
    at onex (F:\CrowdSourcing\src\h5\node_modules\resolve\lib\async.js:92:31)
    at F:\CrowdSourcing\src\h5\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by minwe** [comment]
```
Error: Cannot find module 'react-addons-css-transition-group' from 'F:\CrowdSourcing\src\h5\node_modules\amazeui-touch\lib'
```

不看错误日志的吗？

安装一下 `react-addons-css-transition-group`。

**Comment by xiaohuoni** [comment]
那时候刚入门，什么都不懂。
