### ISSUE TITLE
现在的master版本在meteor下无法运行

### ISSUE THREAD

**Issue by imrememberlee** [amazeui/amazeui-touch#36]
=> Started proxy.                             
=> Started MongoDB.                           
                                              
/home/ben/.meteor/packages/templating/.1.1.8.1pq5bc1++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
TypeError: Cannot convert null to object
    at hasOwnProperty (native)
    at _.has (/home/ben/.meteor/packages/meteor-tool/.1.3.1.2pe85f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:1046:27)
    at ImportScanner._resolveNodeModule (/tools/isobuild/import-scanner.js:727:9)
    at ImportScanner._tryToResolveImportedPath (/tools/isobuild/import-scanner.js:565:12)
    at ImportScanner._resolvePkgJsonMain (/tools/isobuild/import-scanner.js:812:14)
    at ImportScanner._tryToResolveImportedPath (/tools/isobuild/import-scanner.js:576:25)
    at /tools/isobuild/import-scanner.js:333:29
    at _.each._.forEach (/home/ben/.meteor/packages/meteor-tool/.1.3.1.2pe85f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:332:5)
    at /tools/isobuild/import-scanner.js:194:14
    at Array.forEach (native)
    at ImportScanner.scanImports (/tools/isobuild/import-scanner.js:192:22)
    at /tools/isobuild/compiler-plugin.js:791:17
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:759:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:913:8)
    at /tools/isobuild/bundler.js:680:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:671:18)
    at /tools/isobuild/bundler.js:2512:14
    at /tools/isobuild/bundler.js:2602:20
    at Array.forEach (native)
    at Function._.each._.forEach (/home/ben/.meteor/packages/meteor-tool/.1.3.1.2pe85f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2601:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2493:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12

请问一下，我现在的主程序是使用 react ^15.0.1 版本所以 使用amazeui-touch 0.1.0-beta2 会出现 react版本冲突

**Comment by minwe** [comment]
你把 amazeui-touch 目录下面的 `node_modules` 里面的 react 删掉试试。

**Comment by imrememberlee** [comment]
ok 删掉是可行的 谢谢
